--- 
uri: http://rubyforge.org
is_private: false
username: username
cookie_jar: /Users/kef/.rubyforge/cookie.dat
password: password
full_name: Paul O'Keeffe
email: pgokeeffe@gmail.com
github_username: kef
